// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
  

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgzsTE2c0M_3unroouqookFbfGLol5kU',
    appId: '1:722951351272:web:8a182a4f1ecd6386a2525d',
    messagingSenderId: '722951351272',
    projectId: 'restaurante-98ae5',
    authDomain: 'restaurante-98ae5.firebaseapp.com',
    storageBucket: 'restaurante-98ae5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN41DwQ-eCo_mUF7PQz0F30AfjvwYRT6w',
    appId: '1:722951351272:android:40b5d17d1aee7979a2525d',
    messagingSenderId: '722951351272',
    projectId: 'restaurante-98ae5',
    storageBucket: 'restaurante-98ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANcd075F_oqBLFz6SNCs-jhOKt2GdoT1o',
    appId: '1:722951351272:ios:3010565048908970a2525d',
    messagingSenderId: '722951351272',
    projectId: 'restaurante-98ae5',
    storageBucket: 'restaurante-98ae5.appspot.com',
    iosBundleId: 'com.example.learning10c',
  );
}
